Section "InputClass"
  Identifier  "Kensington Wireless Mouse"
  MatchIsPointer "on"
  Driver      "evdev"
  Option      "Name" "Kensington Computer Products Group Orbit Wireless Mobile Trackball"
  Option      "Emulate3Buttons" "yes"
EndSection
